services:
  # The Message Broker
  redis:
    image: redis:alpine
    container_name: redis_queue
    ports:
      - "6379:6379"
    # Persistence: Saves data if container restarts
    volumes:
      - redis_data:/data
    networks:
      - log_network

  # We will add the Go service here later
  # We will add the Python service here later

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - log_network

networks:
  log_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  