services:
  # 1. The Go API
  - type: web
    name: ingestion-service
    env: docker
    rootDir: ingestion-service
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
  

  # 2. The Python Worker
  - type: web
    name: processor-service
    env: docker
    rootDir: processor-service
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false 
      - key: REDIS_URL
        sync: false